(deftheme wombat
  "Medium-contrast faces with a dark gray background.
Adapted, with permission, from a Vim color scheme by Lars H. Nielsen.
Basic, Font Lock, Isearch, Gnus, Message, and Ansi-Color faces
are included.")

(custom-theme-set-faces
 'wombat
 '(cursor ((((class color) (min-colors 89)) (:background "#656565"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#303030"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#454545" :foreground "#ffffff" :underline t))))
 '(region ((((class color) (min-colors 89)) (:background "#444444"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#333366" :foreground "#f6f3e8"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#343434" :foreground "#857b6f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#384048" :foreground "#a0a8b0"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#444444" :foreground "#857b6f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold))))
 '(homoglyph ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#92a65e" :weight bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(help-key-binding ((((class color) (min-colors 89)) (:background "#333333" :foreground "#f6f3e8"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline t))))
 '(button ((((class color) (min-colors 89)) (:background "#333333" :foreground "#f6f3e8"))))
 '(header-line ((((class color) (min-colors 89)) (:background "#303030" :foreground "#e7f6da"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-news-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-news-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#99968b"))))
 '(gnus-group-news-4-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-5-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-mail-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-mail-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-mail-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-cited-text-1 ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#e5786d" :weight bold))))
 '(ansi-color-black ((((class color) (min-colors 89)) (:background "#242424" :foreground "#242424"))))
 '(ansi-color-red ((((class color) (min-colors 89)) (:background "#b85149" :foreground "#b85149"))))
 '(ansi-color-green ((((class color) (min-colors 89)) (:background "#92a65e" :foreground "#92a65e"))))
 '(ansi-color-yellow ((((class color) (min-colors 89)) (:background "#ccaa8f" :foreground "#ccaa8f"))))
 '(ansi-color-blue ((((class color) (min-colors 89)) (:background "#5b98c2" :foreground "#5b98c2"))))
 '(ansi-color-magenta ((((class color) (min-colors 89)) (:background "#64619a" :foreground "#64619a"))))
 '(ansi-color-cyan ((((class color) (min-colors 89)) (:background "#3f9f9e" :foreground "#3f9f9e"))))
 '(ansi-color-white ((((class color) (min-colors 89)) (:background "#f6f3e8" :foreground "#f6f3e8"))))
 '(ansi-color-bright-black ((((class color) (min-colors 89)) (:background "#444444" :foreground "#444444"))))
 '(ansi-color-bright-red ((((class color) (min-colors 89)) (:background "#e5786d" :foreground "#e5786d"))))
 '(ansi-color-bright-green ((((class color) (min-colors 89)) (:background "#95e454" :foreground "#95e454"))))
 '(ansi-color-bright-yellow ((((class color) (min-colors 89)) (:background "#edc4a3" :foreground "#edc4a3"))))
 '(ansi-color-bright-blue ((((class color) (min-colors 89)) (:background "#8ac6f2" :foreground "#8ac6f2"))))
 '(ansi-color-bright-magenta ((((class color) (min-colors 89)) (:background "#a6a1de" :foreground "#a6a1de"))))
 '(ansi-color-bright-cyan ((((class color) (min-colors 89)) (:background "#70cecc" :foreground "#70cecc"))))
 '(ansi-color-bright-white ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#ffffff"))))
 '(default ((((class color) (min-colors 89)) (:background "#242424" :foreground "#f6f3e8"))))
 '(tab-bar ((((class color) (min-colors 89)) (:background "#303030"))))
 '(tab-bar-tab ((((class color) (min-colors 89)) (:background "#242424" :foreground "#f6f3e8" :weight bold :box (:line-width (10 . 10) :style flat-button)))))
 '(tab-bar-tab-inactive ((((class color) (min-colors 89)) (:background "#454545" :foreground "#ffffff" :weight bold :box (:line-width (10 . 10) :style flat-button))))))

(provide-theme 'wombat)
